#### 管理员充电桩故障
POST http://localhost:6480/admin/offCharger
Content-Type: application/json

{
  "pile_id": 1
}

#### 充电桩恢复
POST http://localhost:6480/admin/startCharger
Content-Type: application/json

{
  "pileId": "CFB"
}

#### 查询当前时间
GET http://localhost:6480/timeNow
