### 10. 按天获取账单（以开始时间为准）
<<<<<<<<< Temporary merge branch 1
GET http://localhost:6480/user/checkBill?car_id=tt6
=========
GET http://localhost:6480/user/checkBill?car_id=tt1
>>>>>>>>> Temporary merge branch 2

### 11. 获取详单
GET http://localhost:6480/user/getBill?bill_id=5

### 测试导出账单和详单
GET http://localhost:6480/user/exportAllBill