### request charge
POST http://localhost:6480/user/request
Content-Type: application/json

{
  "car_id": "tt1",
  "request_amount": 90,
  "request_mode": "quick"
}

### modify charge amount
POST http://localhost:6480/user/modifyAmount
Content-Type: application/json

{
  "car_id": "tt2",
  "request_amount": 648
}

### modify charge mode
POST http://localhost:6480/user/chMode
Content-Type: application/json

{
  "car_id": "tt1",
  "request_mode": "quick"
}

### 开始充电
POST http://localhost:6480/user/startCharging
Content-Type: application/json

{
  "car_id": "tt1"
}

### 结束充电
POST http://localhost:6480/user/stopCharging
Content-Type: application/json

{
  "car_id": "tt1"
}


