### request charge
POST http://localhost:6480/user/request
Content-Type: application/json

{
  "car_id": "dick",
  "request_amount": 4.38,
  "request_mode": "slow"
}

### modify charge amount
POST http://localhost:6480/user/modifyAmount
Content-Type: application/json

{
  "car_id": "test",
  "request_amount": 648.88
}

### modify charge mode
POST http://localhost:6480/user/chMode
Content-Type: application/json

{
  "car_id": "test",
  "request_mode": "quick"
}