### correct login
POST http://localhost:6480/user/login
Content-Type: application/json

{
  "username": "xd",
  "password": "xd"
}

### password error
POST http://localhost:6480/user/login
Content-Type: application/json

{
  "username": "test",
  "password": "wrong"
}

### logout
POST http://localhost:6480/user/logout
Content-Type: application/json

{
  "username": "test"
}
