### correct login
POST http://localhost:6480/user/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

### password error
POST http://localhost:6480/user/login
Content-Type: application/json

{
  "username": "test",
  "password": "wrong"
}

