### correct start pile
POST http://localhost:6480/admin/startCharger
Content-Type: application/json

{
  "pileId": "test"
}

### correct shut down pile
POST http://localhost:6480/admin/offCharger
Content-Type: application/json

{
  "pileId": "test"
}


