### signup
POST http://localhost:6480/signup
Content-Type: application/json

{
  "username": "xd",
  "password": "xd",
  "car_id": "dick"
}


### signup existed carId
POST http://localhost:6480/signup
Content-Type: application/json

{
  "username": "wxl",
  "password": "lxw",
  "car_id": "test"
}

