### signup
POST http://localhost:6480/signup
Content-Type: application/json

{
  "username": "xdd",
  "password": "xdd",
  "car_id": "dicks"
}


### signup existed carId
POST http://localhost:6480/signup
Content-Type: application/json

{
  "username": "wxl",
  "password": "lxw",
  "car_id": "test"
}

