### 在这之前，修改http-client.env.json的car，然后，上面Run with选dev。成为全局变量
### signup
POST http://localhost:6480/signup
Content-Type: application/json

{
  "username": "{{car}}",
  "password": "{{car}}",
  "car_id": "{{car}}"
}


### request charge
POST http://localhost:6480/user/request
Content-Type: application/json

{
  "car_id": "{{car}}",
  "request_amount": 6.48,
  "request_mode": "quick"
}


### 开始充电
POST http://localhost:6480/user/startCharging
Content-Type: application/json

{
  "car_id": "{{car}}"
}

### 结束充电
POST http://localhost:6480/user/stopCharging
Content-Type: application/json

{
  "car_id": "{{car}}"
}

### 获取等待状态
GET localhost:6480/user/checkWaitQueue?car_id={{car}}

### 获取充电区队列状态
GET localhost:6480/user/checkStatus?car_id={{car}}

### 修改充电量
POST http://localhost:6480/user/modifyAmount
Content-Type: application/json

{
  "car_id": "{{car}}",
  "request_amount": 648.88
}

### modify charge mode
POST http://localhost:6480/user/chMode
Content-Type: application/json

{
  "car_id": "{{car}}",
  "request_mode": "quick"
}